---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP  # Accessible only within the cluster
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: backend
