---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer  # You can also use NodePort or ClusterIP depending on your setup
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: frontend
