services:
  frontend:
    build:
      context: ../docker/frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Adjust this port as needed
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ../docker/backend
      dockerfile: Dockerfile
    expose:
      - "8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

