apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-app.fullname" . }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "k8s-app.name" . }}
      component: backend
  template:
    metadata:
      labels:
        app: {{ include "k8s-app.name" . }}
        component: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          ports:
            - containerPort: 8080
