apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.image.name }}-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: {{ include "k8s-app.name" . }}
    component: backend
