apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.image.name }}-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{ .Values.frontend.service.nodePort }}
  selector:
    app: {{ include "k8s-app.name" . }}
    component: frontend
