apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-app.fullname" . }}-registry
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: {{ .Values.registry.service.nodePort }}
  selector:
    app: {{ include "k8s-app.name" . }}
    component: registry
